name: Add WIP to PR title

on:
  pull_request:
    types:
      - reopened
      - opened

jobs:
  prepend-wip:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ $TITLE != "[WIP]"* ]]; then
            gh pr edit "$NUMBER" --title "[WIP] $TITLE"
          fi

          gh issue edit $NUMBER --add-label ":construction: WIP" || true
